defaults:
  - base_config
  - _self_



hydra:
  # 1. Disable the creation of the .hydra/ directory (config dumps)
  output_subdir: null
  
  # 2. Prevent creating a new directory for each run
  run:
    dir: .
    
  sweep:
    dir: .
    subdir: .

  # 4. Disable logging completely
  job_logging:
    version: 1
    disable_existing_loggers: false
    root:
      level: OFF
    handlers:
      console:
        class: logging.NullHandler
  
  hydra_logging:
    version: 1
    root:
      level: OFF
    handlers:
      console:
        class: logging.NullHandler