class_path: models.unet.UNet
init_args:
  out_channels: 101
  patch_size: 15
  norm_layer_up: torch.nn.BatchNorm2d
  up_block: models.modules.standard.DoubleConvSkip
  last_opt: torch.nn.Identity
  encoder:
    class_path: models.modules.standard.StandardNet
    init_args:
      in_channels: 12
      depths: [64, 128, 256, 512]
      kernal_sizes: [1, 3]
      initial_stride: 1
      norm_layer: torch.nn.BatchNorm2d
      activation_layer: 
        class_path: torch.nn.ELU
        init_args:
          inplace: True
          alpha: 0.54
      block: models.modules.standard.DoubleConvSkip
      
  upsampling: nearest
  blur_final: False
  blur: False
  final_skip: False
  self_attention: False
  # used in the base model (_base_pl_model.py)
  mask_fc: datasets.transforms.SlopeWCMask
  loss_fc: models.losses.base.Loss #torch.nn.BCELoss # 


  


