class_path: models.xception_s2.XceptionS2
init_args:
  entry_block_filters: [128, 128]
  long_skip: True
  activation_layer: torch.nn.ReLU
  norm_layer: torch.nn.BatchNorm2d
  sepconv_block: models.modules.xception_blocks.DoubleSepConvBlock
  num_sepconv_blocks: 3
  num_sepconv_filters: 128
  mid_block: models.modules.xception_blocks.SepConvBlockSkip
  nonlin_block: models.modules.xception_blocks.DoubleConvBlock
  num_nonlin_blocks: 0
  restrict_rf: True
