# --model.backbone config/model/xception_mix_order.yaml
class_path: models.xception_s2.XceptionS2MixOrder
init_args:
  in_channels: 15
  out_channels: 315
  entry_block_filters: [128, 256]
  long_skip: True
  activation_layer: torch.nn.ReLU
  # activation_layer: 
  #   class_path: torch.nn.ELU
  #   init_args:
  #     inplace: True
  #     alpha: 0.54
  norm_layer: torch.nn.BatchNorm2d
  sepconv_block: models.modules.xception_blocks.DoubleSepConvBlock
  num_sepconv_blocks: 3
  num_sepconv_filters: 512
  mid_block: models.modules.xception_blocks.SepConvBlockSkip
  nonlin_block: models.modules.xception_blocks.DoubleConvBlock
  num_nonlin_blocks: 4
  nonlinear_order: inbetween