keyFile: 'keys/private-key.json'

task: download # download, visualize

init:
  year: 2019
  dataFolder: GEDI${init.year}
  keepLeafOff255: True

download:
  processes: 50


hydra:
  job:
    chdir: False
  run:
    dir: ./logs/${init.dataFolder}_${now:%Y-%m-%d_%H-%M-%S}

