defaults:
  - _self_
  - model: xception_mix_order.yaml


run_id: cg11fpjr # ogzlapu6
bias_correction_column: me_gradual_slope_veg
wandb_project: global-vegetation-structure-v1
model_alias: best

data:
  metadata_file: ~/data/gvs/deploy/deploy_s2_items_2024_part5.parquet
  prediction_dir: ~/data/gvs/deploy/predictions_2024
  tile_id: 20UPD
  patch_size: 512
  border: 16
  img_idx: 0
  n_iamges_per_tile: 20
  predict_full_profile: True
  debug: False
  input_lat_lon: True
  mask_with_scl: True
  output_format: cog
  chunk_size: 512


hydra:
  run:
    dir: ./logs/patch_inference_${data.tile_id}_${now:%Y-%m-%d_%H-%M-%S}