task: download # download, visualize

init:
  year: 2019
  data_dir: GEDI/${init.year}
  n_parallel: 40
  row_group_size: 100 # defines the #partitions when downloading s2
  rewrite: False
  key_file: keys/nrt-key.json


hydra:
  job:
    chdir: False
  run:
    dir: ./logs/${init.data_dir}_${now:%Y-%m-%d_%H-%M-%S}

