defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: none

task: download # download, visualize

init:
  year: 2019
  data_dir: GEDI/${init.year}
  n_parallel: 100
  row_group_size: 100 # defines the #partitions when downloading s2
  rewrite: False
  key_file: keys/nrt-key.json


hydra:
  output_subdir: null #prevent saving the files into .hydra
  job_logging:
    root:
      handlers: [console]
  job:
    chdir: False
  run:
    dir: .