seed_everything: 42
quantize_model: True
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0 # 0.0001
lr_scheduler:
  class_path:  models._scheduler.ChainedScheduler # torch.optim.lr_scheduler.StepLR
  init_args:
    warmup_steps: 6980 # 5 epochs 20 subsets
    T_0: 558400 # for 400 epochs 1 cycle
    eta_min: 1e-6
    max_lr: 0.001
    gamma: 0.2


data:
  class_path: datasets.ffcv_datamodule.FFCVDataModel
  init_args: 
    train_fp: ~/data/GVS/train_subsets/debug0_filtered_v0.beton
    val_fp: ~/data/GVS/train_subsets/debug1_filtered_v0.beton
    cal_fp: ~/data/GVS/train_subsets/val_filtered_v1_1m.beton
    pred_fp:
    test_fp:
    num_workers: 1
    batches_ahead: 3 # affect ram usage
    batch_size: 512 # per device
    order: QUASI_RANDOM
    os_cache: False
    distributed: True

model:
  class_path: models.vs_regression.VSRegression
  init_args:
    feed_slope: False
    zero_slope: True
    slope_th: 20
    zero_out_nonveg: False
    filter_out_nonveg: True
    feed_latlon: True
    evaluate_high_slope: False
    loss_fc: models.losses.quantile_ce_loss.QuantileCELoss
    transform: datasets.transforms.Normalize
    yhat_transform: torch.nn.Identity
    backbone: # --model.backbone config/model/xception_mix_order.yaml

trainer:
  accelerator: gpu
  strategy: auto
    # class_path: lightning.pytorch.strategies.DDPStrategy
    # init_args:
    #   process_group_backend: gloo
  devices: auto
  default_root_dir: logs/wandb
  # val_check_interval: 100000
  # check_val_every_n_epoch: 1
  max_epochs: 200
  num_sanity_val_steps: 0
  reload_dataloaders_every_n_epochs: 1
  # fast_dev_run: 100
  # profiler: advanced
  # profiler: simple
  #   class_path: lightning.pytorch.profilers.PyTorchProfiler
  #   init_args:
  #     sort_by_key: self_cpu_memory_usage
  sync_batchnorm: True
  # enable_checkpointing: False
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: callbacks.qat_export.OnnxExportCallback
    # - class_path: callbacks.regression_metrics_logger.ErrorMetricsLogger
    #   init_args:
    #     log_every: 10
    # - class_path: callbacks.prediction_logger.PredictionLogger
    #   init_args:
    #     log_every: 50
    #     log_batch: 2000
    # - class_path: callbacks.boxplot.BoxplotLogger
    #   init_args:
    #     log_every: 50
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints
        monitor: 'val.loss'
        filename: 'BestModel-{epoch:02d}-{val.loss:.2f}'
        save_top_k: 1
        mode: min
        every_n_epochs: 100 #check every n epochs
        save_last: True # save the last epoch? or just save the last best model?
    # - class_path: callbacks.index_shuffle.IndexShuffler

  logger:
      class_path: callbacks.wandb_logger.WandbLogger
      init_args:
        project: global-vegetation-structure-v1
        name: test
        job_type: train
        save_dir: logs
        log_model: 'all' # 'all' would log the model after each checkpoint being saved
        id:
        resume: False