zone: 32M
year: 2019
n_parallel: 100
partition_size: 64K
save_dir: data/GEDI
rewrite: True
patch_size: 15


hydra:
  job:
    chdir: False
  run:
    dir: ./logs/${zone}_${n_parallel}_${now:%Y-%m-%d_%H-%M-%S}