defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: none

zone: 01G
year: 2019
root_dir:
data_dir: GEDI
save_dir: data/GEDI
rewrite: False
sem_max_release: 100
max_retries: 3
# STEP 0: Repartition GEDI data
repartition: True
partition_size: 512K
partition_name: 'partition_*'

# STEP 1: Sentinel-2 candidates & metadata gather
meta:
  year: ${year}
  data_dir: GEDI/${year}
  save_dir: flash/GEDI_with_s2_candidates/${year}
  S2_meta_dir: scratch/S2_geoparquet_items/${year}
  s2_grid_file: GEDI/Sentinel-2_tilling_shp/sentinel_2_index_shapefile.shp
  n_parallel: 32
  max_cloud_cover: 50
  max_water_percentage: 99
  query_days: 90

# STEP 2: Sentinel-2 best candidates selection
select:
  year: ${year}
  n_parallel: 32
  patch_size: ${patch_size}
  data_dir: flash/GEDI_with_s2_candidates/${year}
  save_dir: scratch/GEDI_with_s2_candidates_and_best/${year}
  S2_meta_dir: scratch/S2_geoparquet_items/${year}
  flag_dir: scratch/Download_flags

# STEP 3: Download patches
download:
  year: ${year}
  n_parallel: 8
  data_dir: scratch/GEDI_with_s2_candidates_and_best/${year}
  save_dir: data/GEDI
  S2_meta_dir: scratch/S2_geoparquet_items/${year}
  wc_dem_meta_dir: GEDI
  patch_size: ${patch_size}


hydra:
  job_logging:
    root:
      handlers: [console]
  job:
    chdir: False
  run:
    dir: .