seed_everything: 42
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0 # 0.0001
lr_scheduler:
  class_path:  models._scheduler.ChainedScheduler # torch.optim.lr_scheduler.StepLR
  init_args:
    warmup_steps: 6980 # 5 epochs 20 subsets
    T_0: 558400 # for 400 epochs 1 cycle
    eta_min: 1e-6
    max_lr: 0.001
    gamma: 0.2


data:
  class_path: datasets.ffcv_datamodule.FFCVDataModel
  init_args: 
    train_fp: ~/data/GVS/train_subsets/debug0_filtered_v0.beton
    val_fp: ~/data/GVS/train_subsets/debug1_filtered_v0.beton
    pred_fp:
    test_fp:
    num_workers: 1
    batches_ahead: 3 # affect ram usage
    batch_size: 512 # per device
    order: QUASI_RANDOM
    os_cache: False
    distributed: True

model:
  class_path: models.unet.UNet
  init_args:
    out_channels: 101
    patch_size: 15
    norm_layer_up: torch.nn.BatchNorm2d
    up_block: models.modules.standard.DoubleConvSkip
    last_opt: torch.nn.Identity
    encoder:
      class_path: models.modules.standard.StandardNet
      init_args:
        in_channels: 12
        depths: [64, 128, 256, 512]
        kernal_sizes: [3, 3]
        initial_stride: 1
        norm_layer: torch.nn.BatchNorm2d
        activation_layer: 
          class_path: torch.nn.ELU
          init_args:
            inplace: True
            alpha: 0.54
        block: models.modules.standard.DoubleConvSkip
        
    upsampling: nearest
    blur_final: False
    blur: False
    final_skip: False
    self_attention: False
    # used in the base model (_base_pl_model.py)
    transform: datasets.transforms.Normalize
    loss_fc: 
      class_path: models.losses.base.MaskedL1Loss #torch.nn.BCELoss # 

trainer:
  accelerator: gpu
  strategy: ddp
    # class_path: lightning.pytorch.strategies.DDPStrategy
    # init_args:
    #   process_group_backend: gloo
  devices: auto
  default_root_dir: logs/wandb
  # val_check_interval: 100000
  # check_val_every_n_epoch: 1
  max_epochs: 200
  num_sanity_val_steps: 0
  reload_dataloaders_every_n_epochs: 1
  # fast_dev_run: 100
  # profiler: advanced
  # profiler: simple
  #   class_path: lightning.pytorch.profilers.PyTorchProfiler
  #   init_args:
  #     sort_by_key: self_cpu_memory_usage
  sync_batchnorm: False
  # enable_checkpointing: False
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    # - class_path: callbacks.regression_metrics_logger.ErrorMetricsLogger
    #   init_args:
    #     log_every: 10
    # - class_path: callbacks.prediction_logger.PredictionLogger
    #   init_args:
    #     log_every: 50
    #     log_batch: 2000
    # - class_path: callbacks.boxplot.BoxplotLogger
    #   init_args:
    #     log_every: 50
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints
        monitor: 'val.loss'
        filename: 'BestModel-{epoch:02d}-{val.loss:.2f}'
        save_top_k: 1
        mode: min
        every_n_epochs: 100 #check every n epochs
        save_last: True # save the last epoch? or just save the last best model?
    # - class_path: callbacks.index_shuffle.IndexShuffler

  logger:
      class_path: callbacks.wandb_logger.WandbLogger
      init_args:
        project: global-vegetation-structure-v1
        name: test
        job_type: train
        save_dir: logs
        log_model: 'all' # 'all' would log the model after each checkpoint being saved
        id: