class_path: models.pl_model.UNet
init_args:
  in_channels: 12
  last_opt:
    class_path: models._model_delta_rhs.DeltaRHRectifier
    init_args:
      rh_idx: 0
      activation:
        class_path: torch.nn.Softplus
        init_args:
          beta: 1
          threshold: 20

