seed_everything: 42
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001

data:
  class_path: datasets._pl_datamodule.PLDataModel
  init_args:
    cache_dir: cache
    data_dir: data/GEDI
    split_files_dir: split_files
    h5_file: merged_h5_test
    use_zones: TEST_ZONES
    batch_size: 64
    num_workers: 8
    pin_memory: True
    shuffle: True
    drop_last: False

trainer:
  accelerator: cpu
  default_root_dir: /tmp/runs
  devices: 1
  max_epochs: 500
  num_sanity_val_steps: 0
  fast_dev_run: True

  logger:
      class_path: callbacks.wandb_logger.WandbLogger
      init_args:
        project: global-vegetation-structure
        name: test
        # job_type: train 
