#%%
rh_type = {f'rh{i}': 'float32' for i in range(100)}
dtypes = {
    'system:index': 'object',
    'beam': 'uint16',
    'delta_time': 'float64',
    'digital_elevation_model': 'float32',
    'digital_elevation_model_srtm': 'float32',
    'elev_highestreturn': 'float32',
    'elev_lowestmode': 'float32',
    'elevation_bias_flag': 'float32',
    'energy_total': 'float32',
    'landsat_treecover': 'float64',
    'landsat_water_persistence': 'uint8',
    'lat_highestreturn': 'float64',
    'lon_highestreturn': 'float64',
    'leaf_off_doy': 'int16',
    'leaf_off_flag': 'uint8',
    'leaf_on_doy': 'int16',
    'leaf_on_cycle': 'uint8',
    'modis_nonvegetated': 'float64',
    'modis_nonvegetated_sd': 'float64',
    'modis_treecover': 'float64',
    'modis_treecover_sd': 'float64',
    'num_detectedmodes': 'uint8',
    'orbit_number': 'int64',
    'pft_class': 'uint8',
    'region_class': 'uint8',
    'selected_algorithm': 'uint8',
    'selected_mode': 'uint8',
    'selected_mode_flag': 'uint8',
    'sensitivity': 'float32',
    'shot_number': 'uint64',
    'solar_azimuth': 'float32',
    'solar_elevation': 'float32',
    'surface_flag': 'uint8',
    'urban_focal_window_size': 'uint8',
    'urban_proportion': 'uint8',
    '.geo': 'object'
}
dtypes.update(rh_type)
# %%
