eval:
  data_path: ../data/calibration-data.parquet
cp:
  alpha: 0.1
  cqr_methods:
    - CQR
    # - CQR-r
    # - CQR-m
    - SE-CQR
  # - SE-CQR-r
  # - SE-CQR-m
  cal_data_path: ../data/calibration-data.parquet
data:
  biome_col: BIOME
  rh_cols:
    0:
      ground_truth: rh0
      q_hi: RH0_Q0
      q_lo: RH0_Q2
      q_med: RH0_Q1
    10:
      ground_truth: rh10
      q_hi: RH10_Q0
      q_lo: RH10_Q2
      q_med: RH10_Q1
    25:
      ground_truth: rh25
      q_hi: RH25_Q0
      q_lo: RH25_Q2
      q_med: RH25_Q1
    50:
      ground_truth: rh50
      q_hi: RH50_Q0
      q_lo: RH50_Q2
      q_med: RH50_Q1
    75:
      ground_truth: rh75
      q_hi: RH75_Q0
      q_lo: RH75_Q2
      q_med: RH75_Q1
    95:
      ground_truth: rh95
      q_hi: RH95_Q0
      q_lo: RH95_Q2
      q_med: RH95_Q1
    98:
      ground_truth: rh98
      q_hi: RH98_Q0
      q_lo: RH98_Q2
      q_med: RH98_Q1
    100:
      ground_truth: rh100
      q_hi: RH100_Q0
      q_lo: RH100_Q2
      q_med: RH100_Q1
  other_cols:
    - lc
    - slope
    - BIOME
    - ECO_ID
    - lat
    - lon
    - geometry
    - shot_number
    - digital_elevation_model
    - solar_elevation
    - sensitivity
    - urban_proportion
    - elevation_bias_flag
    - surface_flag
    - num_detectedmodes
    - selected_mode
    - selected_mode_flag
    - energy_total
    - elev_highestreturn
    - elev_lowestmode
    - beam
